steps:

  ### Build
    - id: 'build'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args: 
        - '-c'
        - |
            docker build -t gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest .
  
  ### Publish
    - id: 'publish'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args: 
        - '-c'
        - |
            docker push gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest
    
    - id: 'tf init'
      name: 'hashicorp/terraform:1.0.0'
      entrypoint: sh
      args: ["-c","terraform init -upgrade "]
    
    - id: 'tf plan'
      name: 'hashicorp/terraform:1.0.0'
      entrypoint: sh
      args: ["-c","ls; terraform plan -out=plan.out"]    
    
    - id: 'tf apply'
      name: 'hashicorp/terraform:1.0.0'
      entrypoint: sh
      args: ["-c","terraform apply plan.out"]    
    
    - id: "deploy"
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'kubectl'
      args: ["apply -f deploy.yml"]
images:
  - 'gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest'