steps:

  ### Build
    - id: 'build'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args: 
        - '-c'
        - |
            docker build -t gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest .
  
  ### Test
    - id: 'test'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args: 
        - '-c'
        - |
            docker run -w "/opt/app" -v "${PWD}:/opt/app" -e CI=true node:alpine yarn test

  ### Publish
    - id: 'publish'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args: 
        - '-c'
        - |
            docker push gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest
  
images:
  - 'gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest'