steps:

  ### Build
    - id: 'build'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args: 
        - '-c'
        - |
            docker build -t gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest .
  
  ### Publish
    - id: 'publish'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args: 
        - '-c'
        - |
            docker push gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest
  
images:
  - 'gcr.io/a37nnunvhmc0oiwh3rx0rwkcl4gr5r/github.com/emanueltud0r/mmcechallenge2023:latest'